#!/bin/bash
# Copyright (c) 2019 Sony Mobile Communications Inc.
# SPDX-License-Identifier: MIT
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# run only on go files
STAGED_GO_FILES=$(git diff --cached --name-only $against | grep "\.go$")
if [ -z "$STAGED_GO_FILES" ]
then
    exit 0
fi
declare -A paths
for f in $STAGED_GO_FILES
do
    paths[$(dirname "$f")]=0
done

echo "--- Pre-commit hook ---"
ok=TRUE
pass=TRUE

echo -e "\n[1] go fmt:"
for f in "${!paths[@]}"
do
    if ! go fmt "./$f/"
    then
        ok=FALSE
        pass=FALSE
    fi
done

if [[ $pass = TRUE ]]
then
    echo -e "\033[0;30m\033[42mSUCCESS\033[0m"
fi


pass=TRUE
echo -e "\n[2] go vet:"
for path in "${!paths[@]}"
do
    if ! go vet "./$path/"
    then
        ok=FALSE
        pass=FALSE
    fi
done
if [[ $pass = TRUE ]]
then
    echo -e "\033[0;30m\033[42mSUCCESS\033[0m"
fi

pass=TRUE
echo -e "\n[3] golangci-lint:"
for f in "${!paths[@]}"
do
    if ! golangci-lint run "./$f/"
    then
        ok=FALSE
        pass=FALSE
        echo -e "\033[0;30m\033[42mSUCCESS\033[0m: $f"
    fi
done
if [[ $pass = TRUE ]]
then
    echo -e "\033[0;30m\033[42mSUCCESS\033[0m"
fi

if [[ $ok = TRUE ]]
then
    echo -e "\n\033[0;30m\033[42mCommit successful. Thanks!\033[0m\n"
    exit 0
fi

echo -e "\n\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
exit 1
